### ISSUE TITLE
Seed File

### ISSUE THREAD

**Issue by brianlmacdonald** [Emotionally-Woken/temphawaiianshirtdepot#7]
For bugs, please include the following:

* What is the expected behavior?
* What is the actual behavior?
* What steps reproduce the behavior?

For features, please specify at least minimal requirements, e.g.:

* "As a developer, I want data to play around with to test."

*'Implentation: a seed file that populates the db with scrub data."

---

*Issue description here…*

**Comment by jvpepino** [comment]
#7 closed.

**Comment by jvpepino** [comment]
closes #7
